//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NecroLens.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NecroLens.Data.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accursed Hoard.
        /// </summary>
        internal static string Chest_Accursed_Hoard {
            get {
                return ResourceManager.GetString("Chest_Accursed_Hoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze Chest.
        /// </summary>
        internal static string Chest_Bronze_Chest {
            get {
                return ResourceManager.GetString("Chest_Bronze_Chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Chest.
        /// </summary>
        internal static string Chest_Gold_Chest {
            get {
                return ResourceManager.GetString("Chest_Gold_Chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mimic.
        /// </summary>
        internal static string Chest_Mimic {
            get {
                return ResourceManager.GetString("Chest_Mimic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Chest.
        /// </summary>
        internal static string Chest_Silver_Chest {
            get {
                return ResourceManager.GetString("Chest_Silver_Chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Chests.
        /// </summary>
        internal static string ConfigWindow_ChestsTab_OpenChests {
            get {
                return ResourceManager.GetString("ConfigWindow_ChestsTab_OpenChests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically opens chest for you once you&apos;re in interaction range.
        ///The plugin only tries to open a chest one time!.
        /// </summary>
        internal static string ConfigWindow_ChestsTab_OpenChests_Details {
            get {
                return ResourceManager.GetString("ConfigWindow_ChestsTab_OpenChests_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPERIMENTAL.
        /// </summary>
        internal static string ConfigWindow_ChestsTab_OpenChests_EXPERIMENTAL {
            get {
                return ResourceManager.GetString("ConfigWindow_ChestsTab_OpenChests_EXPERIMENTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the following chests:.
        /// </summary>
        internal static string ConfigWindow_ChestsTab_OpenFollowingChests {
            get {
                return ResourceManager.GetString("ConfigWindow_ChestsTab_OpenFollowingChests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze.
        /// </summary>
        internal static string ConfigWindow_ChestsTab_OpenFollowingChests_Bronze {
            get {
                return ResourceManager.GetString("ConfigWindow_ChestsTab_OpenFollowingChests_Bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        internal static string ConfigWindow_ChestsTab_OpenFollowingChests_Gold {
            get {
                return ResourceManager.GetString("ConfigWindow_ChestsTab_OpenFollowingChests_Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoards.
        /// </summary>
        internal static string ConfigWindow_ChestsTab_OpenFollowingChests_Hoards {
            get {
                return ResourceManager.GetString("ConfigWindow_ChestsTab_OpenFollowingChests_Hoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        internal static string ConfigWindow_ChestsTab_OpenFollowingChests_Silver {
            get {
                return ResourceManager.GetString("ConfigWindow_ChestsTab_OpenFollowingChests_Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open unsafe chests.
        /// </summary>
        internal static string ConfigWindow_ChestsTab_OpenUnsafeChests {
            get {
                return ResourceManager.GetString("ConfigWindow_ChestsTab_OpenUnsafeChests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even open chests which can be Mimics on the current floor.
        /// </summary>
        internal static string ConfigWindow_ChestsTab_OpenUnsafeChests_Details {
            get {
                return ResourceManager.GetString("ConfigWindow_ChestsTab_OpenUnsafeChests_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight the following objects once near:.
        /// </summary>
        internal static string ConfigWindow_ESPTab_HighlightObjects {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_HighlightObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passage.
        /// </summary>
        internal static string ConfigWindow_ESPTab_HighlightObjects_Passage {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_HighlightObjects_Passage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure Chests.
        /// </summary>
        internal static string ConfigWindow_ESPTab_HighlightObjects_TreasureChests {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_HighlightObjects_TreasureChests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vestige.
        /// </summary>
        internal static string ConfigWindow_ESPTab_HighlightObjects_Votife {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_HighlightObjects_Votife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the following treasure coffers in the overlay:.
        /// </summary>
        internal static string ConfigWindow_ESPTab_HighlightTreasureChests {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_HighlightTreasureChests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze Chests.
        /// </summary>
        internal static string ConfigWindow_ESPTab_HighlightTreasureChests_Bronze {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_HighlightTreasureChests_Bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Chests.
        /// </summary>
        internal static string ConfigWindow_ESPTab_HighlightTreasureChests_Gold {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_HighlightTreasureChests_Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accursed Hoards.
        /// </summary>
        internal static string ConfigWindow_ESPTab_HighlightTreasureChests_Hoards {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_HighlightTreasureChests_Hoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Chests.
        /// </summary>
        internal static string ConfigWindow_ESPTab_HighlightTreasureChests_Silver {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_HighlightTreasureChests_Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show aggro range.
        /// </summary>
        internal static string ConfigWindow_ESPTab_ShowAggroRange {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_ShowAggroRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw sight-, proximity- and sound-range.
        ///Sound Mobs will also have hit box..
        /// </summary>
        internal static string ConfigWindow_ESPTab_ShowAggroRange_Details {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_ShowAggroRange_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximity and Sight.
        /// </summary>
        internal static string ConfigWindow_ESPTab_ShowAggroRange_Proximity_and_Sight {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_ShowAggroRange_Proximity_and_Sight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        internal static string ConfigWindow_ESPTab_ShowAggroRange_Sound {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_ShowAggroRange_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show interaction range for coffers.
        /// </summary>
        internal static string ConfigWindow_ESPTab_ShowCofferInteractionRange {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_ShowCofferInteractionRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you approach a treasure coffer a light circle shows up the maximum distance to open..
        /// </summary>
        internal static string ConfigWindow_ESPTab_ShowCofferInteractionRange_Details {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_ShowCofferInteractionRange_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Arrow on Patrol.
        /// </summary>
        internal static string ConfigWindow_ESPTab_ShowPatrolArrow {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_ShowPatrolArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw an arrow pointing in movement direction..
        /// </summary>
        internal static string ConfigWindow_ESPTab_ShowPatrolArrow_Details {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_ShowPatrolArrow_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Player Dot.
        /// </summary>
        internal static string ConfigWindow_ESPTab_ShowPlayerDot {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_ShowPlayerDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A little dot showing your hit box..
        /// </summary>
        internal static string ConfigWindow_ESPTab_ShowPlayerDot_Details {
            get {
                return ResourceManager.GetString("ConfigWindow_ESPTab_ShowPlayerDot_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Debug Information.
        /// </summary>
        internal static string ConfigWindow_ExtrasTab_ShowDebugInformation {
            get {
                return ResourceManager.GetString("ConfigWindow_ExtrasTab_ShowDebugInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the ID for elements. 
        ///Please turn this on before you submit a bug report. 
        ///It helps me to identify problems faster..
        /// </summary>
        internal static string ConfigWindow_ExtrasTab_ShowDebugInformation_Details {
            get {
                return ResourceManager.GetString("ConfigWindow_ExtrasTab_ShowDebugInformation_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically open in DeepDungeon.
        /// </summary>
        internal static string ConfigWindow_GeneralTab_AutomaticallyOpen {
            get {
                return ResourceManager.GetString("ConfigWindow_GeneralTab_AutomaticallyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Main window when you enter a DeepDungeon.
        ///It shows some handy information and quick access to Settings..
        /// </summary>
        internal static string ConfigWindow_GeneralTab_AutomaticallyOpen_Details {
            get {
                return ResourceManager.GetString("ConfigWindow_GeneralTab_AutomaticallyOpen_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable ESP Overlay.
        /// </summary>
        internal static string ConfigWindow_GeneralTab_EnableOverlay {
            get {
                return ResourceManager.GetString("ConfigWindow_GeneralTab_EnableOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws the ESP overlay showing the positions of Chests, Mobs and all aggro ranges.
        ///You can configure everything you want to see under ESP Settings.
        ///Important: The ESP can only show objects in the games render distance.
        ///This is fixed and CAN NOT be changed!.
        /// </summary>
        internal static string ConfigWindow_GeneralTab_EnableOverlay_Details {
            get {
                return ResourceManager.GetString("ConfigWindow_GeneralTab_EnableOverlay_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable OpenChests.
        /// </summary>
        internal static string ConfigWindow_GeneralTab_OpenChests {
            get {
                return ResourceManager.GetString("ConfigWindow_GeneralTab_OpenChests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPERIMENTAL FEATURE
        ///Automatically opens chest for you once you&apos;re in interaction range.
        ///By default it will NOT open chests which can be Mimics this set!
        ///
        ///This feature can cause your character being stuck next to a chest!
        ///If this happens disable this feature..
        /// </summary>
        internal static string ConfigWindow_GeneralTab_OpenChests_Details {
            get {
                return ResourceManager.GetString("ConfigWindow_GeneralTab_OpenChests_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string ConfigWindow_Language {
            get {
                return ResourceManager.GetString("ConfigWindow_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string ConfigWindow_Language_de {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client-Language.
        /// </summary>
        internal static string ConfigWindow_Language_default {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string ConfigWindow_Language_en {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string ConfigWindow_Language_fr {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string ConfigWindow_Language_ja {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        internal static string ConfigWindow_Language_ko {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        internal static string ConfigWindow_Language_zh {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chests.
        /// </summary>
        internal static string ConfigWindow_Tab_Chests {
            get {
                return ResourceManager.GetString("ConfigWindow_Tab_Chests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESP Settings.
        /// </summary>
        internal static string ConfigWindow_Tab_ESPSettings {
            get {
                return ResourceManager.GetString("ConfigWindow_Tab_ESPSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        internal static string ConfigWindow_Tab_Extras {
            get {
                return ResourceManager.GetString("ConfigWindow_Tab_Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string ConfigWindow_Tab_General {
            get {
                return ResourceManager.GetString("ConfigWindow_Tab_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NecroLens Configuration.
        /// </summary>
        internal static string ConfigWindow_Title {
            get {
                return ResourceManager.GetString("ConfigWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affluence.
        /// </summary>
        internal static string MainWindow_CurrentFloorEffects_Affluence {
            get {
                return ResourceManager.GetString("MainWindow_CurrentFloorEffects_Affluence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteration.
        /// </summary>
        internal static string MainWindow_CurrentFloorEffects_Alteration {
            get {
                return ResourceManager.GetString("MainWindow_CurrentFloorEffects_Alteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight.
        /// </summary>
        internal static string MainWindow_CurrentFloorEffects_Flight {
            get {
                return ResourceManager.GetString("MainWindow_CurrentFloorEffects_Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortune.
        /// </summary>
        internal static string MainWindow_CurrentFloorEffects_Fortune {
            get {
                return ResourceManager.GetString("MainWindow_CurrentFloorEffects_Fortune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety.
        /// </summary>
        internal static string MainWindow_CurrentFloorEffects_Safety {
            get {
                return ResourceManager.GetString("MainWindow_CurrentFloorEffects_Safety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sight.
        /// </summary>
        internal static string MainWindow_CurrentFloorEffects_Sight {
            get {
                return ResourceManager.GetString("MainWindow_CurrentFloorEffects_Sight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Floor Effects:.
        /// </summary>
        internal static string MainWindow_CurrentFloorEffects_Title {
            get {
                return ResourceManager.GetString("MainWindow_CurrentFloorEffects_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor: {0}.
        /// </summary>
        internal static string MainWindow_Floor {
            get {
                return ResourceManager.GetString("MainWindow_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active on next Floor.
        /// </summary>
        internal static string MainWindow_NextFloorMark_ActiveNextFloor {
            get {
                return ResourceManager.GetString("MainWindow_NextFloorMark_ActiveNextFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to open the nearest chest to you..
        /// </summary>
        internal static string MainWindow_OpenChestButton_Help {
            get {
                return ResourceManager.GetString("MainWindow_OpenChestButton_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Chests.
        /// </summary>
        internal static string MainWindow_OpenChests {
            get {
                return ResourceManager.GetString("MainWindow_OpenChests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Open Chests respecting your settings.
        ///
        ///IMPORTANT:
        ///If you&apos;re stuck near a chest and cant move anymore disable this option!.
        /// </summary>
        internal static string MainWindow_OpenChests_Help {
            get {
                return ResourceManager.GetString("MainWindow_OpenChests_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string MainWindow_PassageStatus_Closed {
            get {
                return ResourceManager.GetString("MainWindow_PassageStatus_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MainWindow_PassageStatus_Open {
            get {
                return ResourceManager.GetString("MainWindow_PassageStatus_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passage:.
        /// </summary>
        internal static string MainWindow_PassageStatus_Title {
            get {
                return ResourceManager.GetString("MainWindow_PassageStatus_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respawns: {0}.
        /// </summary>
        internal static string MainWindow_Respawns {
            get {
                return ResourceManager.GetString("MainWindow_Respawns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Aggro.
        /// </summary>
        internal static string MainWindow_ShowAggro {
            get {
                return ResourceManager.GetString("MainWindow_ShowAggro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times:.
        /// </summary>
        internal static string MainWindow_TimeSet_Title {
            get {
                return ResourceManager.GetString("MainWindow_TimeSet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string MainWindow_TrapStatus_Active {
            get {
                return ResourceManager.GetString("MainWindow_TrapStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string MainWindow_TrapStatus_Inactive {
            get {
                return ResourceManager.GetString("MainWindow_TrapStatus_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traps:.
        /// </summary>
        internal static string MainWindow_TrapStatus_Title {
            get {
                return ResourceManager.GetString("MainWindow_TrapStatus_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string MainWindow_TrapStatus_Visible {
            get {
                return ResourceManager.GetString("MainWindow_TrapStatus_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try top open a Chest near to you..
        /// </summary>
        internal static string PluginCommands_OpenChest_Help {
            get {
                return ResourceManager.GetString("PluginCommands_OpenChest_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the configuration..
        /// </summary>
        internal static string PluginCommands_OpenConfig_Help {
            get {
                return ResourceManager.GetString("PluginCommands_OpenConfig_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the main window..
        /// </summary>
        internal static string PluginCommands_OpenOverlay_Help {
            get {
                return ResourceManager.GetString("PluginCommands_OpenOverlay_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enfeebling Trap.
        /// </summary>
        internal static string Traps_Enfeebling_Trap {
            get {
                return ResourceManager.GetString("Traps_Enfeebling_Trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fae Trap.
        /// </summary>
        internal static string Traps_Fae_Trap {
            get {
                return ResourceManager.GetString("Traps_Fae_Trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impeding Trap.
        /// </summary>
        internal static string Traps_Impeding_Trap {
            get {
                return ResourceManager.GetString("Traps_Impeding_Trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landmine.
        /// </summary>
        internal static string Traps_Landmine {
            get {
                return ResourceManager.GetString("Traps_Landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luring Trap.
        /// </summary>
        internal static string Traps_Luring_Trap {
            get {
                return ResourceManager.GetString("Traps_Luring_Trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odder Trap.
        /// </summary>
        internal static string Traps_Odder_Trap {
            get {
                return ResourceManager.GetString("Traps_Odder_Trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owlet Trap.
        /// </summary>
        internal static string Traps_Owlet_Trap {
            get {
                return ResourceManager.GetString("Traps_Owlet_Trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toad Trap.
        /// </summary>
        internal static string Traps_Toad_Trap {
            get {
                return ResourceManager.GetString("Traps_Toad_Trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trap.
        /// </summary>
        internal static string Traps_Unknown {
            get {
                return ResourceManager.GetString("Traps_Unknown", resourceCulture);
            }
        }
    }
}
