namespace NecroLens.Model;

public enum Pomander
{
    Safety = 1,
    Sight,
    Strength,
    Steel,
    Affluence,
    Flight,
    Alteration,
    Purity,
    Fortune,
    Witching,
    Serenity,
    Rage,
    Lust,
    Intuition,
    Raising,
    Resolution,
    Frailty,
    Concealment,
    Petrification,
    LethargyProtomander,
    StormsProtomander,
    DreadProtomander,
    SafetyProtomander,
    SightProtomander,
    StrengthProtomander,
    SteelProtomander,
    AffluenceProtomander,
    FlightProtomander,
    AlterationProtomander,
    PurityProtomander,
    FortuneProtomander,
    WitchingProtomander,
    SerenityProtomander,
    IntuitionProtomander,
    RaisingProtomander,
}
