name: Build Plugin
on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+.[0-9]+'

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            DALAMUD_HOME: /tmp/dalamud
        
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Get Tag Name
              run: echo "tag=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')" >> $GITHUB_ENV

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '8.x.x'

            - name: Download Dalamud Latest
              run: |
                  wget https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -O ${{ env.DALAMUD_HOME }}.zip
                  unzip ${{ env.DALAMUD_HOME }}.zip -d ${{ env.DALAMUD_HOME }}    

            - name: Restore
              run: dotnet restore

            - name: Build
              run: |
                  dotnet build --no-restore --configuration Release --nologo -p:AssemblyVersion=${{ env.tag }}

            - name: Publish Version
              uses: PunishXIV/dynamis-action@v1
              id: dynamis
              with:
                  plugin_id: 53
                  internal_name: 'NecroLens'
                  version_number: ${{ env.tag }}
                  path: 'NecroLens/bin/x64/Release/NecroLens/latest.zip'
                  type: 'latest'
                  dalamud_version: '10'
              env:
                  PUBLISHER_KEY: ${{ secrets.PUBLISHER_KEY }}
