name: Build Plugin
on:
  push:
    branches: 'main'

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: [ windows-2022 ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-prerelease: true

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Download Dalamud
        if: "!contains(github.event.head_commit.message, '[stg]')"
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
          
      - name: Download Dalamud staging
        if: "contains(github.event.head_commit.message, '[stg]')"
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
          
      - name: Build
        run: msbuild NecroLens.sln /p:Configuration=Release /target:NecroLens

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          path: ./NecroLens/bin/x64/Release/*